test/integration: catch failed await in lint test
Often the test failed with timeout. Catch exceptions
(most likely due to unresolved promise)
and fail explicitly.

  1 failing
    1) Go Extension Tests (GOPATH mode)
           Linting - lint errors with multiple open files:
	        Error: Timeout of 20000ms exceeded. For async tests and
		hooks, ensure "done()" is called; if returning a
		Promise, ensure it resolves.

Change-Id: I894ed74fe52442f036ac3637191b7c1d189cbcf1
Reviewed-on: https://go-review.googlesource.com/c/vscode-go/+/418775
Run-TryBot: Hyang-Ah Hana Kim <hyangah@gmail.com>
TryBot-Result: kokoro <noreply+kokoro@google.com>
Reviewed-by: Jamal Carvalho <jamal@golang.org>