eslint: Change test files so eslint does not complain
Remove the old tslint.json files and change all the test files
so that either eslint complaints are fixed by gts fix, or
file-level comments are added to turn the complaints off for now.
(https://github.com/golang/vscode-go/issues/1227)

History of this CL:

trybot succeeded with no changes.

changes to test/gopls/*ts: these failed with
 /workspace/test/gopls/extension.test.ts:39:3
 ERROR: 39:3  semicolon  Unnecessary semicolon
(the tslint style conflicts with the eslint style, which wants semicolons)

now remove tslint.json: that succeeds

add some more linted tests: and as expected that succeeds too

add all the linted test/** files: ok

and now add all the //esline comments:

Change-Id: I9efde901726eb9b28eb5c743e739afbae4508b1e
Reviewed-on: https://go-review.googlesource.com/c/vscode-go/+/291590
Trust: Peter Weinberger <pjw@google.com>
Run-TryBot: Peter Weinberger <pjw@google.com>
TryBot-Result: kokoro <noreply+kokoro@google.com>
Reviewed-by: Hyang-Ah Hana Kim <hyangah@gmail.com>